<?php

declare(strict_types=1);

use App\Support\Database\EnablesRowLevelSecurity;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

/**
 * فروش اقساطی — the schedule, and the rows a shop chases.
 *
 * ## Flat profit, because that is what is quoted
 *
 * An Iranian shop says «۲۰٪ سود روی ۶ قسط». That is a flat markup on the financed
 * amount, not a reducing-balance interest rate, and the two produce different numbers.
 * Modelling it as an APR would be more "correct" and would print a schedule the customer
 * did not agree to. So `profit_percent` is the number on the contract and
 * `profit_amount` is what it came to — both stored, because a percentage without the
 * rial it produced is a figure somebody has to re-derive, and re-derivation is where
 * disagreements start.
 *
 * ## The rows are the plan
 *
 * `total_payable` is stored for the contract, but what is actually owed is the sum of
 * the rows, and the last row carries whatever the division could not split evenly. A
 * schedule whose parts do not add up to its total is one the customer notices on the
 * final payment.
 *
 * ## No `paid_amount` column, deliberately
 *
 * Collection is Phase 7.4 and will bring its own table of receipts. What a row has been
 * paid is then a SUM over those, never a counter on the row (golden rule 3) — a stored
 * figure here would be a second truth about the same money, and the one that drifts.
 *
 * ## Dates are UTC instants, generated by Jalali month arithmetic
 *
 * Stored UTC like everything else (golden rule 5), but the month spacing is computed in the
 * Jalali calendar: a Jalali month is 31, 30 or 29 days, and adding a fixed 30 would put
 * the twelfth instalment days away from the date on the signed contract.
 */
return new class extends Migration
{
    use EnablesRowLevelSecurity;

    public function up(): void
    {
        Schema::create('installment_plans', function (Blueprint $table): void {
            $table->id();
            $table->foreignId('tenant_id')->constrained()->cascadeOnDelete();
            $table->foreignId('branch_id')->constrained()->cascadeOnDelete();

            // Nullable: Phase 7 may schedule a debt that did not come from a sale.
            $table->foreignId('sales_invoice_id')->nullable()->constrained()->nullOnDelete();

            // Never nullable, unlike an invoice's party. Nobody sells on instalments to
            // a walk-in they cannot name.
            $table->foreignId('party_id')->constrained();

            // ضامن. Optional, and a party like any other — a guarantor is usually
            // already a customer of the shop.
            $table->foreignId('guarantor_party_id')->nullable()->constrained('parties')->nullOnDelete();

            $table->string('number');

            // All integer rial (golden rule 2).
            $table->unsignedBigInteger('down_payment')->default(0);
            $table->unsignedBigInteger('principal');
            $table->unsignedSmallInteger('profit_percent')->default(0);
            $table->unsignedBigInteger('profit_amount')->default(0);
            $table->unsignedBigInteger('total_payable');

            $table->unsignedSmallInteger('installment_count');
            $table->unsignedSmallInteger('interval_months')->default(1);
            $table->timestamp('first_due_at');

            $table->string('status')->default('active')->comment('active | settled | defaulted');

            $table->text('notes')->nullable();
            $table->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();

            $table->timestamps();
            $table->softDeletes();

            $table->index(['tenant_id', 'status']);
            $table->index(['tenant_id', 'party_id']);
            $table->unique(['tenant_id', 'number']);
        });

        $this->enableRls('installment_plans');

        DB::statement('alter table installment_plans add constraint installment_plans_count_positive check (installment_count > 0)');

        // One plan per invoice. A second schedule against the same sale would let a shop
        // collect the same debt twice without either plan knowing about the other.
        DB::statement(
            'create unique index installment_plans_invoice_unique
             on installment_plans (tenant_id, sales_invoice_id)
             where sales_invoice_id is not null and deleted_at is null'
        );

        Schema::create('installment_rows', function (Blueprint $table): void {
            $table->id();
            $table->foreignId('tenant_id')->constrained()->cascadeOnDelete();
            $table->foreignId('installment_plan_id')->constrained()->cascadeOnDelete();

            // 1-based, and what the customer's contract calls «قسط سوم».
            $table->unsignedSmallInteger('sequence');

            $table->timestamp('due_at');
            $table->unsignedBigInteger('amount');

            $table->string('status')->default('pending')->comment('pending | paid | overdue');

            $table->timestamps();

            $table->index(['tenant_id', 'due_at']);
            $table->index(['tenant_id', 'installment_plan_id']);
            $table->unique(['tenant_id', 'installment_plan_id', 'sequence']);
        });

        $this->enableRls('installment_rows');

        DB::statement('alter table installment_rows add constraint installment_rows_amount_positive check (amount > 0)');
    }

    public function down(): void
    {
        Schema::dropIfExists('installment_rows');
        Schema::dropIfExists('installment_plans');
    }
};
