<?php

declare(strict_types=1);

namespace App\Support;

use Illuminate\Contracts\Session\Session;
use Random\RandomException;

/**
 * The «کد امنیتی» on the sign-in form: a short code drawn as an SVG, checked once.
 *
 * ## Why not reCAPTCHA or hCaptcha
 *
 * Both are third-party scripts served from hosts that are unreliable or blocked from
 * Iran, and both would put a foreign network dependency in front of the one screen a
 * shopkeeper cannot get past without. This is a couple of kilobytes of SVG generated by
 * our own server: it works offline, it works on a bad connection, and it sends nothing
 * about the visitor anywhere.
 *
 * ## Why the glyphs are `<path>` and not `<text>`
 *
 * This is the whole reason the drawing exists, and it was wrong until 2026-09-05.
 *
 * The first version set each character with an SVG `<text>` element. That renders a
 * picture a person reads — and it also leaves the answer in the document as text, so
 *
 *     document.querySelector('[data-security-image]').textContent   // "WW6CA"
 *
 * solved it. No OCR, no image processing, one line. The obstacle a scripted login had to
 * clear was reading a string out of the page it had already downloaded, which is not an
 * obstacle at all: the check was decoration in front of the only door this product has.
 *
 * So the letters are drawn instead: `self::GLYPHS` is a stroked alphabet on a 10×14 grid
 * and each character becomes a `<path>`. Nothing in the markup spells the code, and the
 * only way back to it is to look at the picture.
 *
 * Vector rather than a GD raster on purpose. GD would need FreeType *and* a TrueType face
 * in the image, and this repository ships its faces as `woff2`, which FreeType cannot
 * read — so a PNG captcha means a new binary asset whose absence breaks sign-in for
 * everybody. Paths need neither, stay crisp at any pixel ratio, and cost ~2KB.
 *
 * ## What it does and does not claim
 *
 * It stops the trivial case: a script POSTing the login form in a loop with a wordlist.
 * It is **not** a defence against an attacker who rasterises the SVG and runs OCR — the
 * noise below is deliberately light, because heavy distortion defeats the shopkeeper long
 * before it defeats the script. And it is not the rate limiter:
 * `LoginRequest::ensureIsNotRateLimited()` is, and it stays. Two cheap independent
 * obstacles beat one clever one.
 *
 * ## The alphabet
 *
 * No `0/O`, `1/I/l`, `5/S`, `2/Z`, `8/B`. A code somebody reads wrong is a code that
 * locks a shopkeeper out of their own till at nine in the morning, and the pairs above
 * are the ones that get read wrong. Five characters, upper case only.
 *
 * Persian digits are deliberately absent: the field accepts what is drawn, the drawing
 * is Latin, and a bidi-reordered code in a text input is unreadable and untypeable.
 */
final class SecurityCode
{
    public const SESSION_KEY = 'security_code';

    /** Characters no two of which are confusable at 22px. */
    private const ALPHABET = 'ACDEFGHJKLMNPQRTUVWXY34679';

    private const LENGTH = 5;

    /**
     * The drawn alphabet: one stroked outline per character on a 10 wide × 14 tall grid,
     * origin top-left, cap line at y=0 and baseline at y=14.
     *
     * Stroked skeletons rather than filled letterforms, because a skeleton is something a
     * person can author, read back and correct — and because `draw()` can then set the
     * apparent stroke weight itself, independently of how far each glyph is scaled.
     *
     * Every entry is checked by `SecurityCodeTest`: the map covers the alphabet exactly,
     * and no path contains a character outside the SVG path grammar.
     */
    private const GLYPHS = [
        'A' => 'M0.6 13.6 L5 0.6 L9.4 13.6 M2.3 8.6 H7.7',
        'C' => 'M9.2 3.4 C8 1.4 6.6 0.6 5 0.6 C2.4 0.6 0.6 3.3 0.6 7.1 C0.6 10.9 2.4 13.6 5 13.6 C6.6 13.6 8 12.8 9.2 10.8',
        'D' => 'M1.6 0.6 V13.6 H4.8 C8 13.6 9.5 10.9 9.5 7.1 C9.5 3.3 8 0.6 4.8 0.6 Z',
        'E' => 'M9 0.6 H1.6 V13.6 H9 M1.6 7.1 H7.4',
        'F' => 'M9 0.6 H1.6 V13.6 M1.6 7.1 H7.4',
        'G' => 'M9.2 3.4 C8 1.4 6.6 0.6 5 0.6 C2.4 0.6 0.6 3.3 0.6 7.1 C0.6 10.9 2.4 13.6 5.1 13.6 C7.6 13.6 9.4 11.8 9.4 9 H5.6',
        'H' => 'M1.6 0.6 V13.6 M8.4 0.6 V13.6 M1.6 7.1 H8.4',
        'J' => 'M8.4 0.6 V9.4 C8.4 12.2 7 13.6 5 13.6 C3 13.6 1.6 12.2 1.6 9.8',
        'K' => 'M1.6 0.6 V13.6 M9.1 0.6 L2.6 7.6 M4.6 5.5 L9.3 13.6',
        'L' => 'M1.6 0.6 V13.6 H9',
        'M' => 'M0.9 13.6 V0.6 L5 8.2 L9.1 0.6 V13.6',
        'N' => 'M1.6 13.6 V0.6 L8.4 13.6 V0.6',
        'P' => 'M1.6 13.6 V0.6 H5.4 C8.2 0.6 9.5 2.2 9.5 4.2 C9.5 6.2 8.2 7.8 5.4 7.8 H1.6',
        'Q' => 'M5 0.6 C2.4 0.6 0.6 3.3 0.6 7.1 C0.6 10.9 2.4 13.6 5 13.6 C7.6 13.6 9.4 10.9 9.4 7.1 C9.4 3.3 7.6 0.6 5 0.6 Z M6.3 10.4 L9.6 13.9',
        'R' => 'M1.6 13.6 V0.6 H5.4 C8.2 0.6 9.5 2.2 9.5 4.2 C9.5 6.2 8.2 7.8 5.4 7.8 H1.6 M5.6 7.8 L9.5 13.6',
        'T' => 'M0.6 0.6 H9.4 M5 0.6 V13.6',
        'U' => 'M1.6 0.6 V9 C1.6 12.2 3 13.6 5 13.6 C7 13.6 8.4 12.2 8.4 9 V0.6',
        'V' => 'M0.6 0.6 L5 13.6 L9.4 0.6',
        'W' => 'M0.3 0.6 L2.7 13.6 L5 5.2 L7.3 13.6 L9.7 0.6',
        'X' => 'M1 0.6 L9 13.6 M9 0.6 L1 13.6',
        'Y' => 'M1 0.6 L5 7.2 L9 0.6 M5 7.2 V13.6',
        '3' => 'M1.1 2.2 C2.3 1 3.6 0.6 5.1 0.6 C7.6 0.6 9.1 1.9 9.1 3.7 C9.1 5.5 7.7 6.8 5.3 6.8 C7.9 6.8 9.4 8.2 9.4 10.2 C9.4 12.3 7.8 13.6 5 13.6 C3.4 13.6 2 13.1 0.8 12.1',
        '4' => 'M7.4 13.6 V0.6 L0.6 9.9 H9.5',
        '6' => 'M8.6 1.8 C7.6 1 6.5 0.6 5.3 0.6 C2.7 0.6 0.65 3.8 0.65 9.15 m0 0 a4.35 4.35 0 1 0 8.7 0 a4.35 4.35 0 1 0 -8.7 0',
        '7' => 'M0.8 0.6 H9.3 L3.9 13.6 M2.2 7.4 H7.4',
        '9' => 'M1.4 12.4 C2.4 13.2 3.5 13.6 4.7 13.6 C7.3 13.6 9.35 10.4 9.35 5.05 m0 0 a4.35 4.35 0 1 0 -8.7 0 a4.35 4.35 0 1 0 8.7 0',
    ];

    /** The drawing's own coordinate space. The rendered size is CSS's business. */
    private const WIDTH = 150;

    private const HEIGHT = 52;

    /**
     * Clear space between the outermost glyph's centre and the edge of the field.
     *
     * A glyph is ~22 units wide once scaled and grows to ~28 when rotated, so a centre
     * closer than this to the edge puts a stroke against the border of `.auth__code-image`
     * — which clips it, because the box is `overflow: hidden`.
     */
    private const MARGIN = 24;

    /**
     * The ink, written as hex rather than read from a design token.
     *
     * A security drawing must look the same to everybody. `currentColor` would let the
     * page theme it, a dark mode invert it and a high-contrast filter flatten it — and an
     * unreadable code is a locked-out shopkeeper. The values are the light-theme
     * `--color-navy` and a slate between it and `--color-navy-mute`; `.auth__code-image`
     * pins the ground under them for the same reason.
     */
    private const INK = '#0e1b2c';

    private const NOISE = '#8c9aab';

    public function __construct(private readonly Session $session) {}

    /**
     * Draw a fresh code, remember it, and return the SVG.
     *
     * Regenerating on every render is the point: a code that survives a reload is a code
     * a script can solve once and replay.
     *
     * @throws RandomException
     */
    public function render(): string
    {
        $code = '';

        for ($i = 0; $i < self::LENGTH; $i++) {
            $code .= self::ALPHABET[random_int(0, strlen(self::ALPHABET) - 1)];
        }

        $this->session->put(self::SESSION_KEY, $code);

        return $this->draw($code);
    }

    /**
     * True when the answer matches the code this session was last shown.
     *
     * Case-insensitive, and Persian or Arabic digits are normalised first — somebody
     * typing on an Iranian keyboard produces «۴» for a drawn `4`, and refusing that is
     * refusing a correct answer. The code is forgotten either way, so a wrong guess
     * costs a new code rather than another attempt at the same one.
     */
    public function check(?string $answer): bool
    {
        $expected = $this->session->pull(self::SESSION_KEY);

        if (! is_string($expected) || ! is_string($answer)) {
            return false;
        }

        $given = mb_strtoupper(trim(Digits::toLatin($answer)));

        return hash_equals($expected, $given);
    }

    /**
     * The code as an inline SVG of paths.
     *
     * Each glyph is placed on its own centre, rotated a little, scaled a little and
     * nudged off the line, so the five are not a row a fixed-window crop can segment.
     * Two curves and a scatter of dashes cross the field underneath them.
     *
     * The noise sits in a lighter ink than the glyphs on purpose. Matching their weight
     * would buy nothing — an attacker already rasterising and thresholding the image can
     * run OCR too — and it would cost the shopkeeper the reading. The obstacle this is
     * meant to be is the one in front of a script that never looks at the picture, and
     * that obstacle is the absence of the answer from the markup, not the ink.
     *
     * @throws RandomException
     */
    private function draw(string $code): string
    {
        $characters = str_split($code);
        $step = (self::WIDTH - 2 * self::MARGIN) / (self::LENGTH - 1);
        $middle = self::HEIGHT / 2;
        $glyphs = '';

        foreach ($characters as $i => $character) {
            // 10 units of glyph become 10 × scale units of drawing; the stroke is divided
            // back out so a smaller glyph is not also a thinner one.
            $scale = random_int(200, 230) / 100;
            $x = self::MARGIN + $step * $i + random_int(-2, 2);
            $y = $middle + random_int(-3, 3);

            $glyphs .= sprintf(
                '<path d="%s" transform="translate(%s %s) rotate(%d) scale(%s) translate(-5 -7)" stroke-width="%s"/>',
                self::GLYPHS[$character],
                $this->number($x),
                $this->number($y),
                random_int(-13, 13),
                $this->number($scale),
                $this->number(2.5 / $scale),
            );
        }

        return sprintf(
            '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 %d %d" width="%d" height="%d" '
            .'role="img" aria-label="کد امنیتی">'
            .'<g fill="none" stroke="%s" stroke-width="1.4" stroke-linecap="round">%s</g>'
            .'<g fill="none" stroke="%s" stroke-linecap="round" stroke-linejoin="round">%s</g>'
            .'</svg>',
            self::WIDTH,
            self::HEIGHT,
            self::WIDTH,
            self::HEIGHT,
            self::NOISE,
            $this->noise(),
            self::INK,
            $glyphs,
        );
    }

    /**
     * The curves and dashes the glyphs sit on.
     *
     * @throws RandomException
     */
    private function noise(): string
    {
        $noise = '';

        for ($i = 0; $i < 2; $i++) {
            $noise .= sprintf(
                '<path d="M0 %d Q %d %d %d %d T %d %d"/>',
                random_int(10, 42),
                (int) (self::WIDTH / 4), random_int(2, 50),
                (int) (self::WIDTH / 2), random_int(10, 42),
                self::WIDTH, random_int(10, 42),
            );
        }

        for ($i = 0; $i < 16; $i++) {
            $x = random_int(2, self::WIDTH - 6);
            $y = random_int(3, self::HEIGHT - 3);

            $noise .= sprintf(
                '<path d="M%d %d l%d %d"/>',
                $x, $y, random_int(2, 5), random_int(-3, 3),
            );
        }

        return $noise;
    }

    /**
     * A number for an SVG attribute: no locale, no trailing zeroes, no `1.0E-5`.
     *
     * `sprintf('%s', 2.5 / 2.35)` is `1.0638297872340425` and depends on the locale's
     * decimal separator — a comma in the wrong place silently voids the whole transform
     * and the glyph vanishes.
     */
    private function number(float $value): string
    {
        return rtrim(rtrim(number_format($value, 3, '.', ''), '0'), '.');
    }
}
