<?php

declare(strict_types=1);

namespace App\Support;

use Illuminate\Contracts\Session\Session;
use Random\RandomException;

/**
 * The «کد امنیتی» on the sign-in form: a short code drawn as an SVG, checked once.
 *
 * ## Why not reCAPTCHA or hCaptcha
 *
 * Both are third-party scripts served from hosts that are unreliable or blocked from
 * Iran, and both would put a foreign network dependency in front of the one screen a
 * shopkeeper cannot get past without. This is a few hundred bytes of SVG generated by
 * our own server: it works offline, it works on a bad connection, and it sends nothing
 * about the visitor anywhere.
 *
 * ## What it does and does not claim
 *
 * It stops the trivial case: a script POSTing the login form in a loop with a wordlist.
 * It is **not** a defence against a determined attacker with an OCR library, and it is
 * not the rate limiter — `LoginRequest::ensureIsNotRateLimited()` is, and it stays. Two
 * cheap independent obstacles beat one clever one.
 *
 * ## The alphabet
 *
 * No `0/O`, `1/I/l`, `5/S`, `2/Z`, `8/B`. A code somebody reads wrong is a code that
 * locks a shopkeeper out of their own till at nine in the morning, and the pairs above
 * are the ones that get read wrong. Five characters, upper case only.
 *
 * Persian digits are deliberately absent: the field accepts what is drawn, the drawing
 * is Latin, and a bidi-reordered code in a text input is unreadable and untypeable.
 */
final class SecurityCode
{
    public const SESSION_KEY = 'security_code';

    /** Characters no two of which are confusable at 22px. */
    private const ALPHABET = 'ACDEFGHJKLMNPQRTUVWXY34679';

    private const LENGTH = 5;

    public function __construct(private readonly Session $session) {}

    /**
     * Draw a fresh code, remember it, and return the SVG.
     *
     * Regenerating on every render is the point: a code that survives a reload is a code
     * a script can solve once and replay.
     *
     * @throws RandomException
     */
    public function render(): string
    {
        $code = '';

        for ($i = 0; $i < self::LENGTH; $i++) {
            $code .= self::ALPHABET[random_int(0, strlen(self::ALPHABET) - 1)];
        }

        $this->session->put(self::SESSION_KEY, $code);

        return $this->draw($code);
    }

    /**
     * True when the answer matches the code this session was last shown.
     *
     * Case-insensitive, and Persian or Arabic digits are normalised first — somebody
     * typing on an Iranian keyboard produces «۴» for a drawn `4`, and refusing that is
     * refusing a correct answer. The code is forgotten either way, so a wrong guess
     * costs a new code rather than another attempt at the same one.
     */
    public function check(?string $answer): bool
    {
        $expected = $this->session->pull(self::SESSION_KEY);

        if (! is_string($expected) || ! is_string($answer)) {
            return false;
        }

        $given = mb_strtoupper(trim(Digits::toLatin($answer)));

        return hash_equals($expected, $given);
    }

    /**
     * The code as an inline SVG.
     *
     * Each character is rotated and offset a little, and two curves cross the field, so a
     * naive pixel-match cannot read it. Deliberately mild: heavy distortion defeats the
     * shopkeeper before it defeats the script, and this is a second obstacle rather than
     * the only one.
     *
     * @throws RandomException
     */
    private function draw(string $code): string
    {
        $w = 132;
        $h = 44;
        $step = $w / (self::LENGTH + 1);
        $glyphs = '';

        foreach (str_split($code) as $i => $char) {
            $x = $step * ($i + 1) + random_int(-3, 3);
            $y = $h / 2 + random_int(-2, 2);
            $angle = random_int(-14, 14);
            $size = random_int(23, 27);

            $glyphs .= sprintf(
                '<text x="%d" y="%d" font-size="%d" font-family="ui-monospace, monospace" '
                .'font-weight="700" text-anchor="middle" dominant-baseline="central" '
                .'fill="#0e1b2c" transform="rotate(%d %d %d)">%s</text>',
                $x, $y, $size, $angle, $x, $y, $char
            );
        }

        $lines = '';

        for ($i = 0; $i < 2; $i++) {
            $lines .= sprintf(
                '<path d="M0 %d Q %d %d %d %d T %d %d" stroke="#46586d" stroke-width="1.5" '
                .'fill="none" opacity="0.5"/>',
                random_int(8, 36), $w / 4, random_int(2, 42), $w / 2,
                random_int(8, 36), $w, random_int(8, 36)
            );
        }

        return sprintf(
            '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 %d %d" width="%d" height="%d" '
            .'role="img" aria-label="کد امنیتی">%s%s</svg>',
            $w, $h, $w, $h, $lines, $glyphs
        );
    }
}
